---
title: "Phyloseq Assignment"
author: "Priya Suresh (15992143)"
date: "April 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(phyloseq)
load("phyloseq_object.RData")   
source("https://bioconductor.org/biocLite.R")
biocLite("phyloseq")
library(phyloseq)
load ("phyloseq_object.RData")
load("~/Documents/MICB425_portfolio/.RData")

metadata = read.table(file="Saanich.metadata.txt", header=TRUE, row.names=1, sep="\t")

#Excercise 1
ggplot(metadata, aes(x=NH4_uM, y=Depth_m)) +
 geom_point(color="purple", shape=17)

##Excercise 2
metadata %>%
  mutate(Temperature_F= Temperature_C*9/5+32)
metadata %>% 
  mutate(Temperature_F= Temperature_C*9/5+32) %>% 
  ggplot() + geom_point(aes(x=Temperature_F, y=Depth_m))
#ggplot with dplyr
library(phyloseq)
load("phyloseq_object.RData")
physeq
plot_bar(physeq, fill="Phylum")
physeq_percent = transform_sample_counts(physeq, function(x) 100 * x/sum(x))
plot_bar(physeq_percent, fill="Phylum")
plot_bar(physeq_percent, fill="Phylum") + 
  geom_bar(aes(fill=Phylum), stat="identity")

plot_bar(physeq, fill="Phylum")
physeq_percent = transform_sample_counts(physeq, function(x) 100 * x/sum(x))
plot_bar(physeq_percent, fill="Phylum")
plot_bar(physeq_percent, fill="Phylum") + 
  geom_bar(aes(fill=Phylum), stat="identity")


physeq_percent = transform_sample_counts(physeq, function(x) 100 * x/sum(x))
plot_bar(physeq_percent, fill="Class",  title="Class from 10-200m 
in Saanich Inlet") +
  geom_bar(aes(fill=Class), stat="identity") + labs(x="Sample depth", y="percent relative abundance")
  
#Faceting notes
plot_bar(physeq_percent, fill="Phylum") +
  geom_bar(aes(fill=Phylum), stat="identity") +
  facet_wrap(~Phylum)
plot_bar(physeq_percent, fill="Phylum") +
  geom_bar(aes(fill=Phylum), stat="identity") +
  facet_wrap(~Phylum, scales="free_y") +
  theme(legend.position = "none")

#Exercise 4

library(dplyr)
metadata %>%
  select(Depth_m, O2_uM, PO4_uM, SiO2_uM, NO3_uM, NH4_uM, NO2_uM) %>% 
  gather(Nutrients, Concentration, O2_uM, PO4_uM, SiO2_uM, NO3_uM, NH4_uM, NO2_uM) %>%
ggplot(aes(x=Depth_m, y=Concentration)) +
  geom_point() + geom_line() + facet_wrap(~Nutrients, scales="free_y") + 
  theme(legend.position= "none")
```

